In [30]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [4]:
data=datasets.load_wine()

In [6]:
df=pd.DataFrame(data.data,data.target)

In [8]:
df.head(4)

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
0  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
0  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
0  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   

       12  
0  1065.0  
0  1050.0  
0  1185.0  
0  1480.0

In [13]:
df.tail(4)

0     1     2     3      4     5     6     7     8     9     10    11  \
2  13.40  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.3  0.70  1.56   
2  13.27  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.2  0.59  1.56   
2  13.17  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.3  0.60  1.62   
2  14.13  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.2  0.61  1.60   

      12  
2  750.0  
2  835.0  
2  840.0  
2  560.0

In [10]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [11]:
data.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [14]:
x=data.data

In [15]:
y=data.target

In [17]:
df.shape

(178, 13)

In [18]:
x.shape

(178, 13)

In [19]:
y.shape

(178,)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
model=svm.SVC()

In [22]:
model.fit(x_train,y_train)

SVC()

In [23]:
model

SVC()

In [26]:
predictions=model.predict(x_test)

In [29]:
print(predictions)

[0 0 1 0 1 0 1 2 2 2 0 1 0 1 0 1 1 1 0 1 0 1 2 2 1 1 1 2 1 0 0 1 2 0 0 0]


In [27]:
acc=accuracy_score(y_test,predictions)

In [28]:
acc

0.8055555555555556

In [31]:
scaler=StandardScaler()

In [32]:
scaler.fit(x)

StandardScaler()

In [33]:
scaler.transform(x)

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [39]:
# input_data=(14.23,	1.71,	2.43,	15.6,	127.0,	2.80,	3.06,	0.28,	2.29,	5.64,	1.04,	3.92	,1065.0)

In [45]:
input_data=(14.13,	4.10,	2.74,	24.5,	96.0,	2.05,	0.76,	0.56,	1.35,	9.2,	0.61,	1.60,	560.0)

In [46]:
as_array=np.asarray(input_data)

In [47]:
reshaped=as_array.reshape(1,-1)

In [50]:
std_data=scaler.transform(reshaped)

In [49]:
model.predict(std_data)

array([1])